### PR TITLE
Small fixes to EN locale.

### PR DESCRIPTION
**Pull request by Septiple**
Just a few spelling and capitalisation fixes. I also fixed the startup tip, so it now mentions Pyrrhic victory as the victory condition.

King once said on the Discord that he welcomes pull requests, so I set out to fix whatever localisation issues I could find. I have similar commits for the other mods, if this one gets accepted.

### CODE REVIEW

**Review by oorzkws — APPROVED** [review]

**Comment by oorzkws** [comment]
Thanks!

**Comment by Septiple** [comment]
Happy to help! I'll get the other commits in soonish too.

One minor typo I noticed in your commit: it looks like you changed it into "Pyanodon'ss", instead of "Pyanodon's"...

**Comment by oorzkws** [comment]
I swear I edited that part out... I guess I made the same mistake twice 😩

**Comment by Septiple** [comment]
This resolves issue 78 BTW @oorzkws: https://github.com/pyanodon/pybugreports/issues/78

I am putting this in the commit message from now on, per King's request.

**Pull request merged**
