### PR TITLE
Codex changes and addons

### PR DESCRIPTION
**Pull request by MrJakobLaich**
Added "voiding buildings" information to codex
Added settings (include_laggy_calculations setting for example)

### CODE REVIEW

**Comment by notnotmelon** [comment]
Some issues

1. "Include laggy calculations" shouldn't be configurable. This flag only exists so that certain calculations are not updated every second. For example we update time of day and playtime every second. There's no need to create a setting for this since toggling it wouldn't improve UPS.

2. Why are we adding a stat for void buildings placed? It's easy to count this value from the production statistics.

3. JPlanet statistics should be added via remote interface, instead of added directly to pyCP. Currently there is no remote interface for this, but it should be added.

4. "Count all buildings on all surfaces" was an oversight on my part. It should count on all surfaces by default. However, I don't want to make a setting for this. Generally we keep a minimal amount of mod settings. Adding a bunch of random settings will just confuse people.

**Comment by MrJakobLaich** [comment]
> Some issues
> 
> 1. "Include laggy calculations" shouldn't be configurable. This flag only exists so that certain calculations are not updated every second. For example we update time of day and playtime every second. There's no need to create a setting for this since toggling it wouldn't improve UPS.
> 2. Why are we adding a stat for void buildings placed? It's easy to count this value from the production statistics.
> 3. JPlanet statistics should be added via remote interface, instead of added directly to pyCP. Currently there is no remote interface for this, but it should be added.
> 4. "Count all buildings on all surfaces" was an oversight on my part. It should count on all surfaces by default. However, I don't want to make a setting for this. Generally we keep a minimal amount of mod settings. Adding a bunch of random settings will just confuse people.

1) ->Ah okay, didn't know, I figured it's so stuff doesn't update as frequently but didn't know it had a reason for not being a setting
2) -> production statistics are less user friendly than just opening the codex and looking up the number, TL;DR khool_hwip on the discord asked for a way to prove they didn't void anything, I figured people frequently talk about voiding/no-void runs, so having it in the codex would be nice
3) -> fair, I figured to have a remove interface would be nice but I'm not _that_ fluid with the py suite GUI stuff yet to implement it, maybe if I ever get bored I'll look into this
4) -> fair, settings vs no settings are just personal preference
I think having more settings is better, I think as long as the settings have a good name and a good description people won't be confused by them

But in the end I don't really care too much about any of these points, I just figured I might as well PR the changes in case some of it makes sense in the suite 👍

**Comment by MrJakobLaich** [comment]
I could change the stuff you listed if you want

**Comment by notnotmelon** [comment]
Sounds good :+1: I can work on the remote interface tomorrow if it will help you.

A "no-voiding" run is an interesting challenge idea. My recommendation is to make a separate mod for this though.
It will need a few features
1. disable the recipes for flare stack, burner, tailings pond, and sinkhole
2. set operable = false for pipes, storage tanks, pumps, and fluid wagons (to prevent flushing)
3. shooting chests will spill the contents onto the floor instead of deleting them
4. prevent mining pipes, storage tanks, fluid wagons, flamethrower turrets, pumps, and assemblers if they have fluid inside

**Comment by MrJakobLaich** [comment]
true, would actually be interesting to do, I'll make a channel for it in the PyDev discord for now 👍

**Pull request closed without merging**
