### PR TITLE
Add improved milestones preset for milestones mod

### PR DESCRIPTION
**Pull request by chunkybanana**
This adds an improved milestones mod preset for the full pyAE suite. While one already exists within the milestones mod, this one is more comprehensive, including stuff like higher tiers of machines/modules, and various intermediate progression steps going through each science pack.

Currently, this overrides the default preset by requiring pypostprocessing as a required mod (milestones prioritises based on dependency count). If this is going to be maintained the one in the milestones mod should probably be removed at some point.

### CODE REVIEW

**Comment by notnotmelon** [comment]
Please update the changelog for all PRs

**Comment by notnotmelon** [comment]
Does this remove the existing milestones provided by Wimbiweb?

**Comment by chunkybanana** [comment]
Yes, this replaces the existing preset provided by wiwiweb for pyAE. It doesn't do anything to the pyAL and med-py presets.

**Comment by notnotmelon** [comment]
Merged. Thank you.

**Pull request merged**
