### PR TITLE
Added menu simulations for PyAL and PyAE

### PR DESCRIPTION
**Pull request by Septiple**
Here they are at last then. These things take longer to make than I expected... I made 3 for AL and 3 for AE. I would like to eventually make a few for every mod, but let's get some feedback first on the ones I have already.

I tried to pick an approximate science level for each of the simulations and use entities accordingly, to hopefully make it seem semi-real. My brother thinks it's too static and that there should be more action/moving things on the screen, but I'm worried that a) that'll make it too cluttered, and b) it's just not how Py works most of the time. A lot of recipes just take a while to finish, and I can't put too many buildings on the screen. I can fake offscreen buildings using offscreen inserters though of course. Let me know what you prefer.

The menu simulations are basically just save games. I make them as a scenario in an editor first, with wooden boxes to outline the viewable area etc. I then play the scenario, set up any scripted entities, and make a save at the perfect moment. Let me know if you want to make some changes so you don't have to suffer through editing the save game directly.

A potential problem is that each save game is fairly large, normally around 3MB each. I think this is because it contains every item and recipe name in case you change your mods. I brought it down to 2MB by making a limited world size of 2 by 4 chunks, you don't see the rest anyway unless you zoom out. The menu simulations from the base game seem to use a different file format than a save game which is much smaller, but I don't know how to generate anything in that format. Space Exploration just uses save files too like me.

The result of the large save files is that if you want 3 menu simulations for each mod, you already use 3 * 8 * 2 MB = 48MB. That's much bigger than most of the Py mods, but much smaller than the graphics mods. Maybe these menu simulations should therefore be put in their own mod, like SE?

I hope Py can make a replacement for the Factorio logo for each of the mods BTW, so I can put them in each simulation, just like Space Exploration has its own logo.

Small side notes:
- oil and gas power plants don't give off a lot of light at night, would be cool to change that. I didn't add lamps around them in my simulation, hoping they'd light up, but they don't...
- the caravan doesn't seem to work in menu simulation mode, so in the PyAL early game sim it walks off but never comes back... Not a big deal though I guess.
- I noticed zungrors get disabled from PyAL when you don't have PyAE installed, is that intended? Otherwise I'd have showcased those instead of xenos.

### CODE REVIEW

**Comment by oorzkws** [comment]
Hm what are your thoughts on white listing the vanilla sims that aren't broken and then just using those in the rotation with the new ones?

Also might be worth adding an Easter egg:
https://old.reddit.com/r/factorio/comments/lgaq6m/til_you_can_use_ctrlnumpad_plusminus_hotkeys_to/

**Comment by Septiple** [comment]
Glad to hear you liked them. I’ll continue making them for the rest of the mods then. Will incorporate any logos that Py makes.

I realize I disable all other menu simulations unconditionally here, so anyone not running PyAL will just get the Factorio PNG as background in the menu. I’ll fix that for when I have more simulations (which could take weeks btw).

I’ll go through the current simulations, and categorize them into those that work, those that break and those that involve biters. I’ve avoided any military related elements in the sims since Py is not balanced with biters after all. In my opinion, it definitely makes sense to leave some of them in when you’re not using all the mods. However, given that Py is a pretty complete overhaul, it makes sense to me that the full Py pack also replaces all simulations. Happy to do whatever though. SE disables them all by default, but it’s a startup config item to leave them in.

Regarding Easter eggs: I’ve tried to hide something behind the menu for all of the sims. Adding Easter eggs when zooming out is hard due to the limited map size I used to get the file size down, but maybe I can do a few things if I use notnotmelon’s suggestion.

Having a single save file with all the simulations is a great idea. We should be able to load the save even if some of the mods are not present I think (and then we disable the relevant camera position). The only problem I see is that you have to choose one of these:
- have several sims load the same file. Probably won’t fix your lag spikes when loading the file…
- have a single long sim that jumps through different camera points. Unfortunately, there’s apparently no way to have randomness within a sim (I read in a comment in SE), so you’d go through the camera points in the same sequence every time, which makes them much less fun to watch. Maybe you have ideas on this notnotmelon?

Regardjng the heliostat tower, that was the first thing I wanted to add, but it’s too big to fit the screen. I’ve since added a load of buildings partly on the screen to suggest a larger base, so I’ll definitely revisit it.

**Comment by notnotmelon** [comment]
>have a single long sim that jumps through different camera points. Unfortunately, there’s apparently no way to have randomness within a sim (I read in a comment in SE), so you’d go through the camera points in the same sequence every time, which makes them much less fun to watch. Maybe you have ideas on this notnotmelon?

Perhaps instead of 1 huge sim world, 1 world per mod. This way we can still view the mods in a random order. Additionally there would be no artifacts when playing without AL or AE

**Comment by Septiple** [comment]
Closing this pull request, will make a new one when I'm done. We probably shouldn't merge that pull request either if the saves are then moved to the graphics mods, so that the save files don't end up stuck in git history, but we'll cross that bridge when we get to it.

**Comment by notnotmelon** [comment]
Sounds good. Py has started work on the logo graphic.

**Comment by notnotmelon** [comment]
image

**Comment by Septiple** [comment]
Nice! I was expecting him to turn those Py icons we have per mod into ingame objects, but this is even better I think.

I don’t have access to the dev versions of the graphics packs (which is fine), so I’ll wait till the next release and incorporate it into the simulations.

**Comment by pyamods** [comment]
Thanks amazing

**Comment by Septiple** [comment]
Glad you like it Py :)

**Pull request closed without merging**
